spring:
  application:
    name: news-app-backend
  datasource:
    url: jdbc:h2:mem:news
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true